### ISSUE TITLE
maybe a small bug in threshold.from_cv function

### ISSUE THREAD

**Issue by iamownt** [jamesdolezal/biscuit#3]
Greatly appreciate your contribution by implementing UQ in medical AI and there seems a small bug in threshold.from_cv function. 

https://github.com/jamesdolezal/biscuit/blob/2092635bd39b3c2bc6f792ece2c4bc5db1f5a7c7/biscuit/threshold.py#L530-L531

**Comment by jamesdolezal** [comment]
Thank you for the bug report! This has now been fixed and merged with `main`.
